---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
        - name: healthcare
          image: balu777kb/healthcare:1
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: healthcare
